### ISSUE TITLE
PIN size can't be higher than a int size

### ISSUE THREAD

**Issue by lonk** [RoopeHakulinen/cordova-plugin-mifare-ultralight#7]
Hi !

As long as, in Java, a int has a limited size, the function "intToByteArray" can't handle pin code higher than 2147483647.

I'm a newbie in Java, but is there a way to easily fix it ?

Thank you !

**Comment by RoopeHakulinen** [comment]
Hey @lonk and thanks for the report! I took a quick look into this and it seems that the transceive (used to unlock PIN) data length can be longer than four bytes as you suggest.

The relevant parts of the Android API:
https://developer.android.com/reference/android/nfc/tech/MifareUltralight.html#transceive(byte[])
https://developer.android.com/reference/android/nfc/tech/MifareUltralight#getMaxTransceiveLength()

The current implementation is as follows:
```
private byte[] intToByteArray(int number) {
  return ByteBuffer.allocate(4).putInt(number).array();
}
```
do you think this would work:

```
private byte[] longToByteArray(long number) {
  return ByteBuffer.allocate(8).putLong(number).array();
}
```

I'd be happy to change it if does not cause any problems but I'm not able to debug it for few weeks from now on at least. Would you need this anytime soon or is it okay to see if it would be viable after the PR #5 is merged?

**Comment by lonk** [comment]
Hey,
Excuse me for the delay, I was in a rush this summer !

I think your changes would work, and I can try it this week, I'll keep you informed if they are working ;)

**Comment by RoopeHakulinen** [comment]
Awesome, thanks! :)

**Comment by lonk** [comment]
Hi there ! Sorry again for the delay !
I just opened the PR #9 which fix the issue, it works fine on our project !

**Comment by RoopeHakulinen** [comment]
No worries at all. Happy to merge it once you've taken a look at my comment :)

**Comment by RoopeHakulinen** [comment]
@lonk There's now version 1.0.4 available in the npm. It would be greatly appreciated if you could test that it works as expected :)
